# Generated by Django 6.1 on 2026-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('van', 'Van')], max_length=20)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance')], default='operational', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
